(() => {
"use strict";
const canvas=document.getElementById("gameCanvas"),ctx=canvas.getContext("2d");
const startOverlay=document.getElementById("startOverlay"),gameOverOverlay=document.getElementById("gameOverOverlay"),startButton=document.getElementById("startButton"),restartButton=document.getElementById("restartButton"),soundButton=document.getElementById("soundButton"),finalScore=document.getElementById("finalScore"),bestScoreEl=document.getElementById("bestScore"),statusText=document.getElementById("statusText");
const DPR=Math.min(window.devicePixelRatio||1,2);
let width=960,height=540,floorY=430,running=false,dead=false,lastTime=0,elapsed=0,distance=0,score=0,speed=310,spawnTimer=0,nextSpawn=1.15,shake=0,flash=0,soundOn=true,audioCtx=null,best=Number(localStorage.getItem("sigma67-best")||0);
bestScoreEl.textContent=String(best);
const player={x:120,y:0,size:36,vy:0,gravity:1800,jumpPower:660,grounded:true,rotation:0},obstacles=[],particles=[],stars=[];
const messages=["KEEP GOING","NO SIGNAL","67","SIGMA?","DON'T PANIC","STILL HERE","AGAIN","GOOD."];

function initStars(){stars.length=0;for(let i=0;i<70;i++)stars.push({x:Math.random()*width,y:Math.random()*(floorY-40),size:Math.random()*2+.5,speed:Math.random()*.4+.1});}
function resize(){const rect=canvas.getBoundingClientRect();width=Math.max(320,rect.width);height=width*9/16;canvas.width=Math.round(width*DPR);canvas.height=Math.round(height*DPR);canvas.style.height=`${height}px`;ctx.setTransform(DPR,0,0,DPR,0,0);floorY=height*.79;player.size=Math.max(28,Math.min(40,width*.038));player.x=Math.max(72,width*.13);if(!running)player.y=floorY-player.size;initStars();}
function resetGame(){running=true;dead=false;elapsed=distance=score=spawnTimer=shake=flash=0;speed=Math.max(280,width*.32);nextSpawn=1.1;obstacles.length=particles.length=0;player.y=floorY-player.size;player.vy=0;player.grounded=true;player.rotation=0;startOverlay.classList.add("hidden");gameOverOverlay.classList.add("hidden");statusText.textContent="RUNNING";lastTime=performance.now();requestAnimationFrame(loop);}
function initAudio(){if(!soundOn)return;if(!audioCtx){const A=window.AudioContext||window.webkitAudioContext;if(A)audioCtx=new A()}if(audioCtx&&audioCtx.state==="suspended")audioCtx.resume();}
function beep(freq,duration,type="square",volume=.035){if(!soundOn)return;initAudio();if(!audioCtx)return;const osc=audioCtx.createOscillator(),gain=audioCtx.createGain();osc.type=type;osc.frequency.value=freq;gain.gain.value=volume;osc.connect(gain);gain.connect(audioCtx.destination);const now=audioCtx.currentTime;gain.gain.setValueAtTime(volume,now);gain.gain.exponentialRampToValueAtTime(.0001,now+duration);osc.start(now);osc.stop(now+duration);}
function jump(){if(!running||dead)return;if(player.grounded){player.vy=-player.jumpPower;player.grounded=false;beep(420,.08,"square",.03);for(let i=0;i<6;i++)particles.push({x:player.x+player.size*.5,y:floorY-3,vx:-80-Math.random()*120,vy:-20-Math.random()*80,life:.35+Math.random()*.25,color:i%2?"#49f6ff":"#ff3bf4"});}}
function action(){initAudio();if(!running||dead){resetGame();return}jump();}
function spawnObstacle(){const choice=Math.random(),baseX=width+50;if(choice<.52){const count=Math.random()<.28?2:1,size=Math.max(28,player.size*.88);for(let i=0;i<count;i++)obstacles.push({type:"spike",x:baseX+i*(size*.82),y:floorY,w:size,h:size,passed:false});}else if(choice<.82){const w=player.size*1.15,h=player.size*(.9+Math.random()*1.05);obstacles.push({type:"block",x:baseX,y:floorY-h,w,h,passed:false});}else{const size=Math.max(26,player.size*.8);obstacles.push({type:"spike",x:baseX,y:floorY,w:size,h:size,passed:false},{type:"spike",x:baseX+size*1.9,y:floorY,w:size,h:size,passed:false});}}
function collides(p,o){const px=p.x+5,py=p.y+5,pw=p.size-10,ph=p.size-10;if(o.type==="block")return px<o.x+o.w&&px+pw>o.x&&py<o.y+o.h&&py+ph>o.y;const sx=o.x+o.w*.18,sy=o.y-o.h*.82,sw=o.w*.64,sh=o.h*.82;return px<sx+sw&&px+pw>sx&&py<sy+sh&&py+ph>sy;}
function die(){dead=true;running=false;shake=12;flash=1;beep(120,.28,"sawtooth",.06);for(let i=0;i<28;i++)particles.push({x:player.x+player.size/2,y:player.y+player.size/2,vx:(Math.random()-.5)*520,vy:(Math.random()-.65)*420,life:.5+Math.random()*.65,color:i%3===0?"#d7ff52":i%2?"#49f6ff":"#ff3bf4"});if(score>best){best=score;localStorage.setItem("sigma67-best",String(best));bestScoreEl.textContent=String(best)}finalScore.textContent=`SCORE: ${score} // BEST: ${best}`;statusText.textContent="SIGNAL LOST";setTimeout(()=>gameOverOverlay.classList.remove("hidden"),420);}
function update(dt){elapsed+=dt;distance+=speed*dt;score=Math.floor(distance/35);speed+=dt*5.2;player.vy+=player.gravity*dt;player.y+=player.vy*dt;if(player.y+player.size>=floorY){player.y=floorY-player.size;player.vy=0;player.grounded=true;player.rotation=Math.round(player.rotation/(Math.PI/2))*(Math.PI/2)}else player.rotation+=dt*5.8;spawnTimer+=dt;if(spawnTimer>=nextSpawn){spawnTimer=0;spawnObstacle();const difficulty=Math.min(.38,elapsed*.004);nextSpawn=.95+Math.random()*.85-difficulty}
for(let i=obstacles.length-1;i>=0;i--){const o=obstacles[i];o.x-=speed*dt;if(!o.passed&&o.x+o.w<player.x){o.passed=true;beep(720,.035,"square",.012)}if(o.x+o.w<-80){obstacles.splice(i,1);continue}if(collides(player,o)){die();return}}
for(const star of stars){star.x-=speed*dt*star.speed;if(star.x<-4){star.x=width+Math.random()*80;star.y=Math.random()*(floorY-40)}}
for(let i=particles.length-1;i>=0;i--){const p=particles[i];p.life-=dt;p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=450*dt;if(p.life<=0)particles.splice(i,1)}
if(shake>0)shake=Math.max(0,shake-dt*28);if(flash>0)flash=Math.max(0,flash-dt*4);}
function drawBackground(){const grad=ctx.createLinearGradient(0,0,width,height);grad.addColorStop(0,"#030306");grad.addColorStop(.55,"#080312");grad.addColorStop(1,"#020607");ctx.fillStyle=grad;ctx.fillRect(0,0,width,height);ctx.globalAlpha=.65;for(const s of stars){ctx.fillStyle=s.size>1.7?"#49f6ff":"#777";ctx.fillRect(s.x,s.y,s.size,s.size)}ctx.globalAlpha=1;const horizon=floorY-20;ctx.strokeStyle="rgba(73,246,255,.12)";ctx.lineWidth=1;const gridOffset=-(distance*.28)%60;for(let x=gridOffset;x<width;x+=60){ctx.beginPath();ctx.moveTo(width/2+(x-width/2)*.2,horizon);ctx.lineTo(x,height);ctx.stroke()}for(let y=horizon;y<height;y+=26){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(width,y);ctx.stroke()}const wordIndex=Math.floor(elapsed/3.3)%messages.length;ctx.globalAlpha=.08;ctx.fillStyle="#ff3bf4";ctx.font=`bold ${Math.max(34,width*.075)}px monospace`;ctx.textAlign="center";ctx.fillText(messages[wordIndex],width*.68,height*.35);ctx.globalAlpha=1;ctx.textAlign="left";}
function drawWorld(){ctx.fillStyle="#0b0b0b";ctx.fillRect(0,floorY,width,height-floorY);ctx.fillStyle="#49f6ff";ctx.fillRect(0,floorY,width,3);for(const o of obstacles){if(o.type==="spike"){ctx.beginPath();ctx.moveTo(o.x,floorY);ctx.lineTo(o.x+o.w/2,floorY-o.h);ctx.lineTo(o.x+o.w,floorY);ctx.closePath();ctx.fillStyle="#ff3bf4";ctx.fill();ctx.strokeStyle="#ffd3fb";ctx.lineWidth=2;ctx.stroke()}else{ctx.fillStyle="#0c0c0c";ctx.fillRect(o.x,o.y,o.w,o.h);ctx.strokeStyle="#d7ff52";ctx.lineWidth=3;ctx.strokeRect(o.x,o.y,o.w,o.h);}}}
function drawPlayer(){ctx.save();ctx.translate(player.x+player.size/2,player.y+player.size/2);ctx.rotate(player.rotation);ctx.shadowColor="#49f6ff";ctx.shadowBlur=18;ctx.fillStyle="#49f6ff";ctx.fillRect(-player.size/2,-player.size/2,player.size,player.size);ctx.shadowBlur=0;ctx.fillStyle="#050505";const eye=player.size*.13,eyeY=-player.size*.08;ctx.fillRect(-player.size*.25,eyeY,eye,eye);ctx.fillRect(player.size*.12,eyeY,eye,eye);ctx.fillRect(-player.size*.18,player.size*.2,player.size*.36,Math.max(3,player.size*.07));ctx.restore();}
function drawParticles(){for(const p of particles){ctx.globalAlpha=Math.max(0,Math.min(1,p.life*1.7));ctx.fillStyle=p.color;ctx.fillRect(p.x,p.y,5,5)}ctx.globalAlpha=1;}
function drawHUD(){ctx.fillStyle="#f4f4f4";ctx.font=`bold ${Math.max(14,width*.019)}px monospace`;ctx.fillText(`SCORE ${score.toString().padStart(5,"0")}`,18,30);ctx.fillStyle="#8e8e8e";ctx.font=`${Math.max(10,width*.012)}px monospace`;ctx.fillText(`SPEED ${Math.round(speed)}`,18,48);}
function draw(){ctx.save();if(shake>0)ctx.translate((Math.random()-.5)*shake,(Math.random()-.5)*shake);drawBackground();drawWorld();drawPlayer();drawParticles();drawHUD();if(flash>0){ctx.fillStyle=`rgba(255,255,255,${flash*.45})`;ctx.fillRect(0,0,width,height)}ctx.restore();}
function loop(now){if(!running){draw();return}const dt=Math.min(.032,(now-lastTime)/1000||0);lastTime=now;update(dt);draw();if(running)requestAnimationFrame(loop);}
startButton.addEventListener("click",action);restartButton.addEventListener("click",action);soundButton.addEventListener("click",()=>{soundOn=!soundOn;soundButton.textContent=soundOn?"SOUND: ON":"SOUND: OFF";soundButton.setAttribute("aria-pressed",String(soundOn));if(soundOn)beep(520,.06)});
canvas.addEventListener("pointerdown",e=>{e.preventDefault();action()});window.addEventListener("keydown",e=>{if(e.code==="Space"||e.code==="ArrowUp"){e.preventDefault();action()}});window.addEventListener("resize",resize);resize();draw();
})();